### ISSUE TITLE
[BUG] Can't get covid cases for USA

### ISSUE THREAD

**Issue by Mayank-1234-cmd** [binarynightowl/covid19_python#13]
**Describe the bug**
Running ```covid19_data.dataByName("USA").confirmed``` (replace USA with United States of America, United States, etc.. and it just returns keyError)
**To Reproduce**
1. Run ```import covid19_data; covid19_data.dataByName("USA").confirmed;```
2. See error

**Expected behavior**
Give confirmed cases.

**Screenshots**
https://pasteboard.co/JOw7y82.png
**Desktop (please complete the following information):**
Ubuntu 18.04 Bionic
**Additional context**

**Comment by Mayank-1234-cmd** [comment]
My program returned this:
```
An keyerror occured while running:'ANGUILLA'
An keyerror occured while running:'NETHERLANDSANTILLES'
An keyerror occured while running:'ANTARCTICA'
An keyerror occured while running:'ARUBA'
An keyerror occured while running:'BERMUDA'
An keyerror occured while running:'BOUVETISLAND'
An keyerror occured while running:'COCOS[KEELING]ISLANDS'
An keyerror occured while running:'CONGO[DRC]'
An keyerror occured while running:'CONGO[REPUBLIC]'
An keyerror occured while running:"CÔTED'IVOIRE"
An keyerror occured while running:'COOKISLANDS'
An keyerror occured while running:'CAPEVERDE'
An keyerror occured while running:'CHRISTMASISLAND'
An keyerror occured while running:'CZECHREPUBLIC'
An keyerror occured while running:'FALKLANDISLANDS[ISLASMALVINAS]'
An keyerror occured while running:'FAROEISLANDS'
An keyerror occured while running:'FRENCHGUIANA'
An keyerror occured while running:'GUERNSEY'
An keyerror occured while running:'GIBRALTAR'
An keyerror occured while running:'GREENLAND'
An keyerror occured while running:'GUADELOUPE'
An keyerror occured while running:'SOUTHGEORGIAANDTHESOUTHSANDWICHISLANDS'
An keyerror occured while running:'GUINEA-BISSAU'
An keyerror occured while running:'GAZASTRIP'
An keyerror occured while running:'HONGKONG'
An keyerror occured while running:'HEARDISLANDANDMCDONALDISLANDS'
An keyerror occured while running:'ISLEOFMAN'
An keyerror occured while running:'BRITISHINDIANOCEANTERRITORY'
An keyerror occured while running:'JERSEY'
An keyerror occured while running:'KIRIBATI'
An keyerror occured while running:'NORTHKOREA'
An keyerror occured while running:'SOUTHKOREA'
An keyerror occured while running:'CAYMANISLANDS'
An keyerror occured while running:'MACEDONIA[FYROM]'
```

**Comment by Mayank-1234-cmd** [comment]
hello?

**Comment by binarynightowl** [comment]
Hello, the US works fine. Try this line
`covid19_data.dataByName("US").confirmed`

Also please, remember this is a professional forum, its not my job to fix the issue instantly. I am a devloper that has a lot going on, and I cannot fix the issues instantly. 
As for all of the other Key errors, those are all unsupported areas that are not provided by my API. This is because those data points are not provided to me by the data source. If you read the documentation on the readme of this repo or the examples section, you will see the proper way to get the US data. Also, I reccomend using the new method of getting the data which is the object parameter style. Is there anything else I can do for you?

Once again please do not bump isssues, as I cannot always respond right away, and I have been dealing with power outages in my area all day. Thanks for your consideration,
Taylor Dettling

**Comment by Mayank-1234-cmd** [comment]
thanks!
